"""Initial schema

Revision ID: 8b7e4a5927d7
Revises: 
Create Date: 2026-01-27 20:14:51.063176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b7e4a5927d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=False),
    sa.Column('note_purpose', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('project', sa.String(length=255), nullable=False),
    sa.Column('plan_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_note_purpose'), ['note_purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_note_type'), ['note_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_project'), ['project'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_title'), ['title'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.String(length=255), nullable=True),
    sa.Column('path', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_parent_id'), ['parent_id'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('link_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'target_id', 'link_type', name='unique_link_type')
    )
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_links_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_links_target_id'), ['target_id'], unique=False)

    op.create_table('note_tags',
    sa.Column('note_id', sa.String(length=255), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('note_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_tags')
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_links_target_id'))
        batch_op.drop_index(batch_op.f('ix_links_source_id'))

    op.drop_table('links')
    op.drop_table('tags')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_parent_id'))
        batch_op.drop_index(batch_op.f('ix_projects_id'))

    op.drop_table('projects')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_title'))
        batch_op.drop_index(batch_op.f('ix_notes_project'))
        batch_op.drop_index(batch_op.f('ix_notes_plan_id'))
        batch_op.drop_index(batch_op.f('ix_notes_note_type'))
        batch_op.drop_index(batch_op.f('ix_notes_note_purpose'))
        batch_op.drop_index(batch_op.f('ix_notes_id'))

    op.drop_table('notes')
    # ### end Alembic commands ###
